---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: taiga-secrets
  namespace: flux-system
spec:
  interval: 5m
  timeout: 4m
  wait: true
  prune: true
  path: ./apps/sprint/taiga-secrets
  sourceRef:
    kind: GitRepository
    name: stackspout
  dependsOn:
    - name: flux
    - name: secrets-controller
  postBuild:
    substituteFrom:
      - kind: Secret
        name: stackspin-cluster-variables
