---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: penpot
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 2m
  timeout: 10m
  wait: true
  prune: true
  path: ./apps/design/penpot
  sourceRef:
    kind: GitRepository
    name: stackspout
  dependsOn:
    - name: flux
    - name: local-path-provisioner
    - name: penpot-secrets
    - name: nginx
    - name: single-sign-on
  postBuild:
    substituteFrom:
      - kind: Secret
        name: stackspin-cluster-variables
      - kind: ConfigMap
        name: stackspin-penpot-kustomization-variables
      - kind: Secret
        name: stackspin-penpot-variables
      # OIDC
      - kind: Secret
        name: stackspin-penpot-oauth-variables
      - kind: ConfigMap
        name: stackspin-single-sign-on-kustomization-variables
