---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: calcom
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 2m
  timeout: 10m
  wait: true
  prune: true
  path: ./apps/meet/calcom
  sourceRef:
    kind: GitRepository
    name: stackspout
  dependsOn:
    - name: flux
    - name: local-path-provisioner
    - name: calcom-secrets
    - name: nginx
    - name: single-sign-on
  postBuild:
    substitute:
      quote: '"'
    substituteFrom:
      - kind: Secret
        name: stackspin-cluster-variables
      - kind: ConfigMap
        name: stackspin-calcom-kustomization-variables
      - kind: Secret
        name: stackspin-calcom-variables
      # OIDC
      - kind: Secret
        name: stackspin-calcom-oauth-variables
      - kind: ConfigMap
        name: stackspin-single-sign-on-kustomization-variables
