apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vikunja-test-kustomization.yaml
  - vikunja-secrets-kustomization.yaml
  - vikunja-kustomization.yaml
  - vikunja-extra-kustomization.yaml
