---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: add-sign
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  path: ./apps/sign
  sourceRef:
    kind: GitRepository
    name: stackspout
